const foreignBrands = [
	{ id: 67, name: 'BMW' },
	{ id: 68, name: 'Mercedes-Benz' },
	{ id: 70, name: 'Audi' },
	{ id: 71, name: 'Volkswagen' },
	{ id: 72, name: 'Mini' },
	{ id: 77, name: 'Toyota' },
	{ id: 103, name: 'Alfa-Romeo' },
	{ id: 104, name: 'Aston Martin' },
	{ id: 93, name: 'Bentley' },
	{ id: 141, name: 'Bugatti' },
	{ id: 94, name: 'Buick' },
	{ id: 112, name: 'Cadillac' },
	{ id: 101, name: 'Chevrolet' },
	{ id: 115, name: 'Chrysler' },
	{ id: 102, name: 'Citroen' },
	{ id: 79, name: 'Daihatsu' },
	{ id: 237, name: 'DFSK' },
	{ id: 80, name: 'Dodge' },
	{ id: 241, name: 'DS' },
	{ id: 117, name: 'Ferrari' },
	{ id: 122, name: 'Fiat' },
	{ id: 118, name: 'Ford' },
	{ id: 75, name: 'GMC' },
	{ id: 125, name: 'Honda' },
	{ id: 124, name: 'Hummer' },
	{ id: 109, name: 'Infiniti' },
	{ id: 108, name: 'Isuzu' },
	{ id: 110, name: 'Jaguar' },
	{ id: 111, name: 'Jeep' },
	{ id: 81, name: 'Lamborghini' },
	{ id: 82, name: 'Land Rover' },
	{ id: 78, name: 'Lexus' },
	{ id: 87, name: 'Lincoln' },
	{ id: 84, name: 'Lotus' },
	{ id: 88, name: 'Maserati' },
	{ id: 89, name: 'Mazda' },
	{ id: 140, name: 'McLaren' },
	{ id: 91, name: 'Mitsubishi' },
	{ id: 76, name: 'Nissan' },
	{ id: 73, name: 'Peugeot' },
	{ id: 121, name: 'Pontiac' },
	{ id: 120, name: 'Porsche' },
	{ id: 86, name: 'Renault' },
	{ id: 85, name: 'Rolls-Royce' },
	{ id: 83, name: 'Rover' },
	{ id: 95, name: 'SAAB' },
	{ id: 97, name: 'Scion' },
	{ id: 69, name: 'Smart' },
	{ id: 98, name: 'Subaru' },
	{ id: 99, name: 'Suzuki' },
	{ id: 139, name: 'Tesla' },
	{ id: 74, name: 'Volvo' },
]

export default foreignBrands
